### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by galloj** [architector1324/PicoCoin#1]
Hello,
I looked at your project because I wanted to learn about cryptocurrencies and thought that simple or starting projects are good way to learn. So as I am beginner I am not sure if those are really issues, so feel free to correct me.

First thing is that I noticed that you are talking about h_diff as byte, but in examples you are showing that it is half byte. In case that it is half byte, then your tables where you except 64 levels of h_diff are right (as 4*64=256). But in your code you are behaving like it is byte (8*64=512). (Two hex letters represent one byte.) So if I am not wrong, then I would probably recommend that you switch to SHA3-512.

Second thing I noticed is that you are claiming that it is hard to do factorization parallelly. But I think that it would be easy to split the search to equally sized ranges and distribute them between multiple cores or even computers, atleast for basic bruteforce algorithm. But I am not much familiar with all that math about primenumbers, so if there is some not so well parallelizable way, but very fast, then please send me some link about it.

**Comment by architector1324** [comment]
Hello! This project started about 3 days ago just for fun. Thanks for the interest. 

I guess this project is not good for start learning cryptocurrencies, because it is experimental and does not use "best practise".

Yes, you're right about an example, it's wrong. Will be fixed.

Two words about code - it is not ready yet.

About integer factorization - it may be computed in parallel, but not effective, especially for big numbers. RSA still alive because it is not a simple task.

Also, it's recursive there, so it is impossible to compute it in parallel.

**Comment by galloj** [comment]
Yes, I understand that this project probably won't be best practise style, but it is interesting to watch born of something and to see how far it will get. Projects which have best pracitse style usually have already really big codebase so it is hard to learn and usually have reached high level of maturity so I feel like it wouldn't be that interesting. I can atleast on this project help a bit with bugs and so on.

Also can you please explain what do you by the rescusive calculation? Because if it is v_diff, then you had said there that from value 35 it have value 1. But you are right that at value of 256 it probably won't be really worth it atleast for pools if you don't have low network latency. But I still think that it will be worth it minning on multiple cores or GPU.

Also RSA is still alive, but the difference is that it is 2048 bit number. So compared to 256 bit it is 2^1792 times bigger number (in decimal form this would probably be number with 180 decimal places). Also it is composed out of two primes. Because your number which you are factorizing is random it have high chance of having low primes, which reduces the security of it a bit more down too.

So maybe it would be interesting to actually make v_diff slowly grow up or keep constant while make grow of h_diff slower.

**Comment by galloj** [comment]
I am now studying something about primes and thinking about your alogirthm as it is interesting. And I noticed that to verify if block was sucessfully mined you only check if numbers multiplied together are equal to hash. But I think that you should also verify that all of those numbers are actually primes otherwise attacker could claim they solved the problem and as proof supply unfactored number.

**Comment by architector1324** [comment]
Sure, there will be some additional checks. Now it's just an idea, draft design if u want)

**Comment by architector1324** [comment]
> I am now studying something about primes and thinking about your alogirthm as it is interesting. And I noticed that to verify if block was sucessfully mined you only check if numbers multiplied together are equal to hash. But I think that you should also verify that all of those numbers are actually primes otherwise attacker could claim they solved the problem and as proof supply unfactored number.

Sure, there will be some additional checks. Now it's just an idea, draft design if u want)

**Comment by architector1324** [comment]
> Also RSA is still alive, but the difference is that it is 2048 bit number. So compared to 256 bit it is 2^1792 times bigger number (in decimal form this would probably be number with 180 decimal places). Also it is composed out of two primes. Because your number which you are factorizing is random it have high chance of having low primes, which reduces the security of it a bit more down too.

About chance to find prime factor of large number randomly - check out [Prime number theorem](https://en.wikipedia.org/wiki/Prime_number_theorem). In two words it says that probability of finding prime factor of a big number randomly inversely proportional it's natural logarithm.

In out case for `h_diff=14` it's about `0.026` or `2.6%`.

**Comment by galloj** [comment]
Yes, of course I understand it is in early phase of development. I just want to point out possible bugs, so they aren't forgoten there.

Also about prime number theorem, I think it just says what is chance for so big number to be prime. So 2.6% is probability that the solution to the factorization problem will be the number itself. So it got me thinking that interesting thing is that about 1% solutions for h_diff 35 where v_diff is 1 will be really easy to guess as you spam network with like 100 solutions where you calaim that solution to the problem is the number itself. So by this you will get DoS on the network as other peers will have to validate that your number is really a prime and also after they sucessfully validate one of those solutions, everyone one on network will accept that you successfully mined that blog - and you actually haven't done anything else than just compute SHA3 hash and publish the result.

**Comment by galloj** [comment]
Damn. Nevermind that thing which I said about DoS. It is surprisingly fast to check if number is prime (my computer can find about 100 256bit prime numbers per second from random numbers). Looks like I will have to look at those prime numbers a bit more as it is really interesting it is so fast verify they are primes. So all blocks from h_diff 35 to h_diff 64 would probably take just few hours to mine without submiting any proof thats false.

**Comment by architector1324** [comment]
Also, for checking proof of work you not just compute last hash. You are checking hashes from first to last factorization (just look [code](https://github.com/architector1324/PicoCoin/blob/872620001692e01da244be73f3cac543700bbead/core.py#L208) for more details)

**Comment by galloj** [comment]
I am now not really talking about checking the PoW, but about it's generation. https://github.com/architector1324/PicoCoin/blob/main/miner.py#L28 You can replace this line with call to check if number is prime, which is really fast. (Tested it with `sympy.ntheory.isprime`) If it fails, then you just change solver address or padding of json and generate new hash, then again check if it is prime. Then you repeat this till it is prime number and you have the proof done. And it takes just a fraction of second compared to factorization which takes long time.

**Comment by architector1324** [comment]
I'm not sure that understand the idea of generating a proof of work in this way. Provide an example with empty block, as it was done in the README.

Main idea to use number factorization here is that it's hard to generate proof of work and very fast to check the result.
If i understand you idea right, you want to boost up proof of work generation speed, which makes the whole idea meaningless.

**Comment by galloj** [comment]
Exactly, you almost understand it correctly. I just want to say this can be done. Let's imagine network full of people, all of them working on solving the problem and getting reward. But then someone comes and use my algorithm. He can then mine the coins faster than anyone using original algorithm. And noone is able to distinguish between the blocks mined by the ultra fast algorithm and the slow one as both proofs are correct, so the currency is destoryed.

I can try to write the actual code for this, but it will take me some time and it will work only on blocks which have v_diff 1 or maybe it could work for other diffs as well if I use the change of json padding.

**Comment by architector1324** [comment]
> I can try to write the actual code for this, but it will take me some time and it will work only on blocks which have v_diff 1 or maybe it could work for other diffs as well if I use the change of json padding.

I mean you can do it by your self. No need to write code, just show me how it will work.

If it's really can be done in this way, i should change the algo or it's parameters.

**Comment by galloj** [comment]
The probably easiest way to do this is to add another parameter to function `ProofOfWork.extract` and supply this parameter to call of `json.dumps` as `indent`. 
Then change code of those two lines
https://github.com/architector1324/PicoCoin/blob/735d6c00fd3a220bb23bc249953b5e3420844ccf/miner.py#L27-L28
to something like this: (haven't verified it actually works, but it should)
```python
indent = 0
factors = None
while factors == None:
  num = self.block.pow.extract(i,indent)
  if sympy.ntheory.isprime(num):
    indent = {1:num}
  padding++
```
